print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')

print("He said,\"I am a Boy.\"")
print('There is a famous saying in English that "Rome was not built in a day."')
print("Please Enter Your Age:")